name: Release Helm Charts

on:
  push:
    branches:
      - "main"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          fetch: 0

      - name: Confige Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releasers
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.RGITHUB_TOKEN }}"